// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Paradox.Graphics;

namespace SiliconStudio.Paradox.Effects.Modules
{
    public static partial class CopySliceKeys
    {
        public static readonly ParameterKey<Texture> Source = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<float> Slice = ParameterKeys.New<float>();
    }
}
