// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;

namespace SiliconStudio.Paradox.Effects.Modules
{
    public static partial class TerrainBaseKeys
    {
        public static readonly ParameterKey<Texture> HeightMap = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<SamplerState> HeightMapSampler = ParameterKeys.New<SamplerState>();
        public static readonly ParameterKey<Texture> ColorMap = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<float> HeightScale = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> TexelSize = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> TwoTexelSizeOverHeightScale = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> RelativeMarginWidth = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> RelativeEffectivePatchSize = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> HalfTesselation = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> TwoOverTesselation = ParameterKeys.New<float>();
        public static readonly ParameterKey<Vector2[]> MorphConsts = ParameterKeys.New<Vector2[]>();
    }
}
