// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;



#line 1 "D:\Files\Projects\Clockwork\Samples\Terrain\Terrain.Game\Effects\TerrainEffectMain.pdxfx"


#line 3
namespace Terrain.Effects
{
    [DataContract]
#line 5
    public partial class TerrainMaterialParameters : ShaderMixinParameters
    {

        #line 7
        public static readonly ParameterKey<bool> HasPreTransform = ParameterKeys.New<bool>();
    };

    #line 10
    internal static partial class ShaderMixins
    {
        internal partial class TerrainPrepassEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
            {

                #line 12
                context.Mixin(mixin, "ParadoxDefaultLightPrepassEffect");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TerrainPrepassEffect", new TerrainPrepassEffect());
            }
        }
    }

    #line 15
    internal static partial class ShaderMixins
    {
        internal partial class TerrainEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
            {

                #line 19
                if (context.GetParam(TerrainMaterialParameters.HasPreTransform))
                {

                    #line 21
                    context.Mixin(mixin, "PreTransformation");
                }

                #line 24
                context.Mixin(mixin, "ParadoxDefaultDeferredShader");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TerrainEffect", new TerrainEffect());
            }
        }
    }

    #line 27
    internal static partial class ShaderMixins
    {
        internal partial class TerrainTerrainEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
            {

                #line 29
                context.Mixin(mixin, "DefaultDeferredTerrainEffect");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TerrainTerrainEffect", new TerrainTerrainEffect());
            }
        }
    }
}
