// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>


namespace SiliconStudio.Paradox.Effects.Modules
{
    public static partial class VolumeShaderBaseKeys
    {
        public static readonly ParameterKey<uint> SliceCount = ParameterKeys.New<uint>();
    }
}
